---
- name: Installing multi cluster k8s master
  hosts: master
  vars:
   - kubeurl:  'https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch'
   - dockerurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"

  tasks:
  ##### Step1: resolve docker dependency and install docker
    - name: configure yum repo for Docker
      yum_repository:
         name: docker-stable-ce
         description: docker-repo
         baseurl: "{{ dockerurl }}"
         gpgcheck: 0
         enabled: 1
         name: docker-ce

    - name: install container.io package 1.2.2-3 for latest docker 1.19
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.2-3.3.el7.x86_64.rpm
        state: present

    - name: installing python3-pip package for docker docker-py dependency
      yum:
         name: python3-pip
         state: present
    
    # docker-py package is for docker_container ansible module
    - pip:
        name: docker-py

    - name: install docker-ce package
      package:
        name: docker-ce
        state: present

    - name: disable SELinux
      selinux: 
         state: disabled

   # Docker use cgroups docker daemon which is not supported by K8s. 
   # so need to change it to systemd
    - name: changing Docker Daemon
      copy: 
        src: "/tmp/daemon.json"
        dest: "/etc/docker/daemon.json"

    - name: restart docker service
      service:
        name: docker
        state: restarted  
        enabled: yes
    
    - name: Adding firewal rules for docker
      firewalld: 
         masquerade: yes
         state: enabled
         permanent: yes
         zone: public
      
    ######### Step 2: Congiure system for K8s Master.
    - name: disable swap
      command: swapoff -a

    - name: disable automatically at every reboot by adding entry to /etc/rc.d/rc.local
      copy:
        src: "/tmp/rc.local"
        dest: "/etc/rc.d/"

    - name: Giving execute premission to the file rc.local
      file:
        path: /etc/rc.d/rc.local
        state: touch
        mode: a+x

    - name: create Kubernates repository
      yum_repository:
          name: kubernates
          description: Kubernates yum repo
          file: kubernates
          baseurl: "{{ kubeurl }}"
          gpgcheck: 1
          gpgkey:
            - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
            - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
          enabled: 1
          exclude:
            - kubelet
            - kubeadm
            - kubectl

    - name: install kubelet, kubectl and kubeadm
      yum: 
        name: 
          - kubectl
          - kubeadm
          - kubelet
        disable_excludes:
          - kubeadm

    - name: add bridge route to ip6Tables by aadding config file to /etc/sysctl.d/k8s.conf using sysctl module 
      sysctl: 
         name: net.bridge.bridge-nf-call-ip6tables
         value: 1
         state: present
         reload: yes
    - name: add bridge route to ipTables by aadding config file to /etc/sysctl.d/k8s.conf using sysctl module 
      sysctl: 
         name: net.bridge.bridge-nf-call-iptables
         value: 1
         state: present
         reload: yes
      
    - name: start kubelet service
      service: 
         name: kubelet
         state: restarted
         enabled: yes

    - name: adding kubelet service and port to firewalld
      firewalld: 
         port: '10250/tcp'
         premanent: yes
         state: enabled
         zone: public
    
    - name: reload firewalld
      service: 
         name: firewalld
         state: restarted

    - name: restarting docker service
      service:
         name: docker
         state: restarted
    
    - name: describe the master and slave in the /etc/hosts file for master and slave node. 
      copy: 
        src: /tmp/hosts
        dest: /etc/hosts
