---
- name: Sending mail using gmail
  hosts: localhost
  vars_files:
      - /local/mail_pass.txt 
   
  tasks: 
    - name: Using mail module to send email
      mail:
        subject: "This message is for Mini"
        body: "Babu ne thana thaya?"
        from: "{{ from_user }}"
        to: "{{ to_user }}"
        host: smtp.gmail.com
        port: 587
        username: "{{ username }}" 
        password: "{{ passwd }}"
         
