---
- name: taking input during runtime
  hosts: web
  vars_prompt:
    - name: username
      prompt: "What is the username" 

    - name: passwd
      prompt: "kindly enter the password" 

  tasks:  
   - debug: 
       msg: "The user name is: {{ username }}" 
   - debug: 
       msg: "The password is: {{ passwd }}"
