---
- name: intall httpd server
  hosts: web
  vars:
    - url: "https://docs.ansible.com/ansible/latest/modules/get_url_module.html"
    - pkg: httpd 
    - docRoot: "/var/www/deepak"
    - srcHttpdConf: "/local/local.conf"
    - destHttpdConf: "/etc/httpd/conf.d/deepak.conf"
    - downWebPageTo: "/var/www/deepak/index.html"

  tasks:
    - name: installing httpd web server
      package:
         name: "{{ pkg }}"
         state: present
      when: ansible_os_family == "RedHat"
      register: httpd_status

     #create directory for documentRoot
    - name: create dir /var/www/deepak
      file:
        state: directory
        dest: "{{ docRoot }}"
      register: dir

    - name: coping conf file
      template:
        src: "{{ srcHttpdConf }}"
        dest: "{{ destHttpdConf }}"
        mode: 0666
      register: conf
      when: httpd_status.rc == 0
      notify: restart httpd  # notifing handler having name is "restart httpd"

    - name: copy webpage from url
      get_url:
         url: "{{ url }}"
         dest: "{{ downWebPageTo }}"
         mode: 0666
      when: dir.failed == false
      tags: download-web-pages
      notify: restart httpd

  handlers:
       - name: restart httpd
         service:
           name: httpd
           state: restarted

