---

########################################################################
#############  Deploying HTTPD service on EC2 host ##############
- name: Configuring web server on the ec2-host dynamically
  hosts: tag_name_web_server 
  become: true
  vars_files:
      - /root/ansible-playbook/roles/access.key
  roles: 
    - role: webserver
